-- Insert sample service provider applications with all required fields
INSERT INTO service_provider_applications (
  id,
  business_name,
  business_type,
  business_address,
  contact_person,
  contact_email,
  contact_phone,
  service_categories,
  services_offered,
  status,
  priority,
  created_at,
  updated_at
) VALUES
  (
    '660e8400-e29b-41d4-a716-446655440001',
    'Elite Cleaning Services',
    'cleaning_services',
    '123 Business Street, Kuala Lumpur, 50450',
    'John Smith',
    'john.cleaning@example.com',
    '+60123456789',
    ARRAY['cleaning', 'maintenance'],
    ARRAY['Office cleaning', 'Carpet cleaning', 'Window cleaning', 'Deep cleaning'],
    'pending',
    'high',
    now() - interval '2 days',
    now() - interval '2 days'
  ),
  (
    '660e8400-e29b-41d4-a716-446655440002',
    'Garden Paradise Landscaping',
    'landscaping',
    '456 Green Avenue, Petaling Jaya, 47800',
    'Mary Johnson',
    'mary.gardening@example.com',
    '+60198765432',
    ARRAY['landscaping', 'gardening'],
    ARRAY['Garden design', 'Lawn maintenance', 'Tree pruning', 'Irrigation systems'],
    'under_review',
    'normal',
    now() - interval '5 days',
    now() - interval '1 day'
  ),
  (
    '660e8400-e29b-41d4-a716-446655440003',
    'TechFix IT Solutions',
    'technical_services',
    '789 Tech Hub, Cyberjaya, 63000',
    'Ahmed Hassan',
    'ahmed.tech@example.com',
    '+60176543210',
    ARRAY['technical_support', 'maintenance'],
    ARRAY['Network setup', 'Computer repair', 'CCTV installation', 'Smart home systems'],
    'approved',
    'urgent',
    now() - interval '10 days',
    now() - interval '3 days'
  ),
  (
    '660e8400-e29b-41d4-a716-446655440004',
    'Delicious Catering Co',
    'catering',
    '321 Food Street, Shah Alam, 40000',
    'Lisa Wong',
    'lisa.catering@example.com',
    '+60134567890',
    ARRAY['catering', 'food_services'],
    ARRAY['Event catering', 'Daily meal delivery', 'Halal catering', 'Corporate lunches'],
    'additional_info_required',
    'normal',
    now() - interval '7 days',
    now() - interval '2 days'
  ),
  (
    '660e8400-e29b-41d4-a716-446655440005',
    'SecureGuard Security Services',
    'security_services',
    '567 Safety Boulevard, Subang Jaya, 47500',
    'David Kumar',
    'david.security@example.com',
    '+60187654321',
    ARRAY['security', 'safety'],
    ARRAY['Security guard services', 'Access control', 'Event security', 'Patrol services'],
    'rejected',
    'low',
    now() - interval '15 days',
    now() - interval '5 days'
  ),
  (
    '660e8400-e29b-41d4-a716-446655440006',
    'Fresh Mart Grocery Delivery',
    'delivery_services',
    '888 Market Square, Mont Kiara, 50480',
    'Sarah Lee',
    'sarah.freshmart@example.com',
    '+60165554433',
    ARRAY['delivery', 'food_services'],
    ARRAY['Grocery delivery', 'Fresh produce', 'Same-day delivery', 'Bulk orders'],
    'pending',
    'normal',
    now() - interval '1 day',
    now() - interval '1 day'
  );

-- Insert some service provider profiles for approved applications  
INSERT INTO service_provider_profiles (
  id,
  business_name,
  business_type,
  contact_phone,
  contact_email,
  service_categories,
  is_active,
  is_verified,
  compliance_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at
) VALUES
  (
    '770e8400-e29b-41d4-a716-446655440001',
    'TechFix IT Solutions',
    'technical_services',
    '+60176543210',
    'ahmed.tech@example.com',
    ARRAY['technical_support', 'maintenance'],
    true,
    true,
    'compliant',
    4.8,
    24,
    now() - interval '3 days',
    now()
  ),
  (
    '770e8400-e29b-41d4-a716-446655440002',
    'ProClean Professional Services',
    'cleaning_services',
    '+60123334455',
    'info@proclean.com',
    ARRAY['cleaning', 'maintenance'],
    true,
    true,
    'compliant',
    4.5,
    18,
    now() - interval '30 days',
    now() - interval '1 day'
  );