-- Insert sample service provider applications without user dependencies
INSERT INTO service_provider_applications (
  id,
  business_name,
  business_type,
  business_registration_number,
  contact_person,
  contact_email,
  contact_phone,
  business_address,
  service_categories,
  services_offered,
  years_of_experience,
  insurance_coverage,
  license_numbers,
  certifications,
  business_hours,
  coverage_areas,
  pricing_structure,
  equipment_owned,
  emergency_services,
  status,
  priority,
  created_at,
  updated_at
) VALUES
  (
    '660e8400-e29b-41d4-a716-446655440001',
    'Elite Cleaning Services',
    'cleaning_services',
    'REG123456789',
    'John Smith',
    'john.cleaning@example.com',
    '+60123456789',
    '123 Business Street, Kuala Lumpur',
    ARRAY['cleaning', 'maintenance'],
    ARRAY['Office cleaning', 'Carpet cleaning', 'Window cleaning', 'Deep cleaning'],
    5,
    100000.00,
    ARRAY['CL2024001'],
    ARRAY['ISO 9001:2015', 'Green Cleaning Certified'],
    'Mon-Sat 8AM-6PM',
    ARRAY['Kuala Lumpur', 'Selangor'],
    'Hourly rates starting from RM25/hour',
    ARRAY['Vacuum cleaners', 'Pressure washers', 'Cleaning chemicals'],
    true,
    'pending',
    'high',
    now() - interval '2 days',
    now() - interval '2 days'
  ),
  (
    '660e8400-e29b-41d4-a716-446655440002',
    'Garden Paradise Landscaping',
    'landscaping',
    'REG987654321',
    'Mary Johnson',
    'mary.gardening@example.com',
    '+60198765432',
    '456 Green Avenue, Petaling Jaya',
    ARRAY['landscaping', 'gardening'],
    ARRAY['Garden design', 'Lawn maintenance', 'Tree pruning', 'Irrigation systems'],
    8,
    75000.00,
    ARRAY['LS2024002'],
    ARRAY['Certified Landscape Designer', 'Pesticide Application License'],
    'Mon-Fri 7AM-5PM, Sat 8AM-2PM',
    ARRAY['Klang Valley'],
    'Project-based pricing, free consultations',
    ARRAY['Lawn mowers', 'Hedge trimmers', 'Irrigation equipment'],
    false,
    'under_review',
    'normal',
    now() - interval '5 days',
    now() - interval '1 day'
  ),
  (
    '660e8400-e29b-41d4-a716-446655440003',
    'TechFix IT Solutions',
    'technical_services',
    'REG456789123',
    'Ahmed Hassan',
    'ahmed.tech@example.com',
    '+60176543210',
    '789 Tech Hub, Cyberjaya',
    ARRAY['technical_support', 'maintenance'],
    ARRAY['Network setup', 'Computer repair', 'CCTV installation', 'Smart home systems'],
    12,
    200000.00,
    ARRAY['IT2024003', 'CCTV2024001'],
    ARRAY['CISSP', 'CompTIA Network+', 'Cisco Certified'],
    '24/7 Support Available',
    ARRAY['Kuala Lumpur', 'Selangor', 'Putrajaya'],
    'Flat rates + materials, emergency surcharge applies',
    ARRAY['Diagnostic tools', 'Network equipment', 'Installation tools'],
    true,
    'approved',
    'urgent',
    now() - interval '10 days',
    now() - interval '3 days'
  ),
  (
    '660e8400-e29b-41d4-a716-446655440004',
    'Delicious Catering Co',
    'catering',
    'REG321654987',
    'Lisa Wong',
    'lisa.catering@example.com',
    '+60134567890',
    '321 Food Street, Shah Alam',
    ARRAY['catering', 'food_services'],
    ARRAY['Event catering', 'Daily meal delivery', 'Halal catering', 'Corporate lunches'],
    6,
    150000.00,
    ARRAY['FOOD2024001', 'HALAL2024001'],
    ARRAY['HACCP Certified', 'Halal Certification', 'Food Handler Certificate'],
    'Daily 6AM-10PM, 24h advance booking required',
    ARRAY['Klang Valley', 'Negeri Sembilan'],
    'Per person pricing, group discounts available',
    ARRAY['Commercial kitchen equipment', 'Delivery vehicles', 'Catering supplies'],
    false,
    'additional_info_required',
    'normal',
    now() - interval '7 days',
    now() - interval '2 days'
  ),
  (
    '660e8400-e29b-41d4-a716-446655440005',
    'SecureGuard Security Services',
    'security_services',
    'REG789123456',
    'David Kumar',
    'david.security@example.com',
    '+60187654321',
    '567 Safety Boulevard, Subang Jaya',
    ARRAY['security', 'safety'],
    ARRAY['Security guard services', 'Access control', 'Event security', 'Patrol services'],
    15,
    500000.00,
    ARRAY['SEC2024001', 'GUARD2024001'],
    ARRAY['Licensed Security Agency', 'Guard Training Certified', 'First Aid Certified'],
    '24/7 Operations',
    ARRAY['Selangor', 'Kuala Lumpur', 'Putrajaya'],
    'Monthly contracts, hourly rates for events',
    ARRAY['Uniforms', 'Communication equipment', 'Patrol vehicles'],
    true,
    'rejected',
    'low',
    now() - interval '15 days',
    now() - interval '5 days'
  ),
  (
    '660e8400-e29b-41d4-a716-446655440006',
    'Fresh Mart Grocery Delivery',
    'delivery_services',
    'REG555666777',
    'Sarah Lee',
    'sarah.freshmart@example.com',
    '+60165554433',
    '888 Market Square, Mont Kiara',
    ARRAY['delivery', 'food_services'],
    ARRAY['Grocery delivery', 'Fresh produce', 'Same-day delivery', 'Bulk orders'],
    3,
    50000.00,
    ARRAY['DEL2024001'],
    ARRAY['Food Handler License', 'Cold Chain Certified'],
    'Daily 7AM-11PM',
    ARRAY['Mont Kiara', 'TTDI', 'Bangsar'],
    'Delivery fee + 5% service charge',
    ARRAY['Refrigerated vehicles', 'Insulated bags', 'Mobile POS systems'],
    false,
    'pending',
    'normal',
    now() - interval '1 day',
    now() - interval '1 day'
  );

-- Insert some service provider profiles for approved applications
INSERT INTO service_provider_profiles (
  id,
  business_name,
  business_type,
  contact_phone,
  contact_email,
  service_categories,
  coverage_areas,
  is_active,
  is_verified,
  compliance_status,
  average_rating,
  total_reviews,
  created_at,
  updated_at
) VALUES
  (
    '770e8400-e29b-41d4-a716-446655440001',
    'TechFix IT Solutions',
    'technical_services',
    '+60176543210',
    'ahmed.tech@example.com',
    ARRAY['technical_support', 'maintenance'],
    ARRAY['Kuala Lumpur', 'Selangor', 'Putrajaya'],
    true,
    true,
    'compliant',
    4.8,
    24,
    now() - interval '3 days',
    now()
  ),
  (
    '770e8400-e29b-41d4-a716-446655440002',
    'ProClean Professional Services',
    'cleaning_services',
    '+60123334455',
    'info@proclean.com',
    ARRAY['cleaning', 'maintenance'],
    ARRAY['Kuala Lumpur', 'Petaling Jaya'],
    true,
    true,
    'compliant',
    4.5,
    18,
    now() - interval '30 days',
    now() - interval '1 day'
  );