// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nojhdpkixpqniokiusww.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vamhkcGtpeHBxbmlva2l1c3d3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MzQ3NjEsImV4cCI6MjA3MDExMDc2MX0.tm0eoscZOY7AWObpSJPeqL1xukX3erEP3c42ATzMuDU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});